name: Trigger Dependabot on Push

on:
  push:
    branches:
      - "*"  # Run on all branches

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-dependabot
